### ISSUE TITLE
Tradução das tags <p>

### ISSUE THREAD

**Issue by analudias** [reativa/traducao-freecodecamp#60]
Boa tarde, pessoal!

Gostaria de confirmar se é necessário traduzir os conteúdos das tags "p" quando ela está presente no código de solução, por exemplo.

```html
<div id="inner">
  <p>I meet so many people who are in search of that one trick that will help them work smart. Even if you work smart, you still have to work hard.</p>
  <span class="date">1:32 PM - 12 Jan 2018</span>
  <hr>
</div>
```

**Comment by PauloLuan** [comment]
Oi @analudias se estiver animada pode traduzir sim 😉 (mas o mais importante é sempre o enunciado principal)
